#!/bin/bash

# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
#  Created by Sam Deane on 27/02/2020.
#  All code (c) 2020 - present day, Elegant Chaos Limited.
# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

#export RT_REBUILD=true
source Dependencies/ReleaseTools/Scripts/make-tools

echo "***************"
echo "Preparing macOS"
echo "***************"

rt set scheme DelayedStartup-macOS --platform macOS
rt archive --xcconfig Sources/DelayedStartup/Resources/SkipSparkle.xcconfig  | xcpretty
rm -rf ~/Desktop/DelayedStartupNoSparkle.app
ditto ".build/macOS/archive.xcarchive/Products/Applications/xXxprojectxXx.app" ~/Desktop/DelayedStartupNoSparkle.app
open ~/Desktop/DelayedStartupNoSparkle.app
